name: troso
description: Troso mobile app

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  provider: ^6.0.2
  json_annotation: ^4.4.0
  http: 0.13.4
  flutter_stripe: ^2.4.0
  cached_network_image: ^3.2.0
  tflite_flutter: ^0.8.0
  google_fonts: ^2.3.2
  flutter_cube: ^0.1.1
  quickalert: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/jet/Jet.obj
    - assets/shark/shark.obj
    - assets/config/stripe.json
    - assets/images/images1.jpg
    - assets/images/images2.jpg
    - assets/images/images3.jpg
    - assets/images/images4.jpg
    - assets/images/images5.jpg

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-Regular.ttf

